"""DemoBrain and DemoProvider: deterministic demonstration brain.

DEMO MODE — NO REAL AI CONNECTED.

DemoBrain produces scripted, deterministic plans for a small set of
canonical goals.  It clearly identifies itself as a demo and never
claims to be a real language model or connected AI service.

This is NOT a real LLM.  It CANNOT reason about arbitrary goals.
It exists to demonstrate the multi-agent orchestration pipeline
end-to-end in a controlled, repeatable way.

Supported canonical goals (case-insensitive substring match):
  - "network" / "connectivity"       → network status demo plan
  - "remember" / "memory" / "name"   → memory storage demo plan
  - "security" / "safe" / "threat"   → defensive security demo plan
  - "check" / "status" / "system"    → system check demo plan
  - "report" / "summary" / "health"  → system check demo plan
  - "plan" / "next steps" / "prepare"→ planning demo plan
  - anything else                    → generic demo plan
"""

from __future__ import annotations

from ..agent.brain import AIProvider, Brain, BrainUnavailableError
from .models import (
    AgentReport,
    CodeChange,
    ExecutionReport,
    ImprovementProposal,
    Plan,
    PlanStep,
)


DEMO_PROVIDER_NAME = "demo"
DEMO_LABEL = "DEMO MODE — NO REAL AI CONNECTED"


class DemoProvider(AIProvider):
    """Deterministic demo AI provider.

    Returns scripted responses for a small set of known patterns.
    Always identifies outputs as demo-generated.
    """

    @property
    def provider_name(self) -> str:
        return DEMO_PROVIDER_NAME

    def complete(self, prompt: str) -> str:
        """Return a deterministic demo response (not AI-generated)."""
        return (
            f"[{DEMO_LABEL}]\n"
            "This is a scripted demo response. "
            "No language model processed this prompt."
        )

    def is_available(self) -> bool:
        return True


class DemoBrain(Brain):
    """Deterministic Brain implementation for demo/testing purposes.

    Produces scripted plans that exercise the full orchestration pipeline
    without requiring a real AI provider.  All outputs are clearly labelled
    as DEMO.

    All demo steps use safe tool invocations (echo / time) — no destructive
    actions, no external network calls, no file writes.
    """

    @property
    def provider_name(self) -> str:
        return DEMO_PROVIDER_NAME

    def is_available(self) -> bool:
        return True

    def plan(self, goal: str, context: tuple[str, ...] = ()) -> Plan:
        """Produce a deterministic demo plan for the given goal."""
        steps = self._select_steps(goal)
        return Plan(
            goal=f"[{DEMO_LABEL}] {goal}",
            steps=tuple(steps),
            provider=self.provider_name,
        )

    def generate_code(self, request: "CodeGenerationRequest") -> tuple[CodeChange, ...]:  # type: ignore[name-defined]
        """Return a trivial demo code change — clearly labelled."""
        return (
            CodeChange(
                path=request.allowed_files[0] if request.allowed_files else "demo_change.py",
                content=(
                    f"# {DEMO_LABEL}\n"
                    f"# Demo code change for goal: {request.goal}\n"
                    "# This file was NOT generated by a real AI.\n"
                ),
            ),
        )

    def propose_improvement(
        self,
        report: ExecutionReport,
        context: tuple[str, ...] = (),
    ) -> ImprovementProposal:
        """Return a scripted improvement proposal — clearly labelled."""
        return ImprovementProposal(
            title=f"[{DEMO_LABEL}] Demo improvement for: {report.goal}",
            rationale=(
                "This is a scripted demo proposal. "
                "A real AI would analyze the execution report and generate improvements."
            ),
            changes=(),
            provider=self.provider_name,
        )

    # ------------------------------------------------------------------
    # Goal routing
    # ------------------------------------------------------------------

    def _select_steps(self, goal: str) -> list[PlanStep]:
        """Select a scripted step list based on goal keywords.

        Network is checked before generic "check" to avoid misrouting
        "Check network status" to the system-check flow.
        """
        gl = goal.lower()
        if any(kw in gl for kw in ("network", "connectivity", "connection", "internet", "wifi")):
            return self._network_steps()
        if any(kw in gl for kw in ("remember", "memory", "my name", "name is", "store", "recall")):
            return self._memory_steps(goal)
        if any(kw in gl for kw in ("security", "safe", "threat", "suspicious", "scan", "posture", "vuln")):
            return self._security_steps()
        if any(kw in gl for kw in ("check", "status", "behav", "normal", "system", "report", "summary", "health")):
            return self._system_check_steps()
        if any(kw in gl for kw in ("plan", "next step", "prepare", "todo", "roadmap")):
            return self._planning_steps()
        return self._generic_steps(goal)

    # ------------------------------------------------------------------
    # Step libraries
    # ------------------------------------------------------------------

    def _system_check_steps(self) -> list[PlanStep]:
        """Three-step system status check: collect → analyze → report."""
        return [
            PlanStep(
                identifier="demo-collect",
                objective="Collect local system status snapshot [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] System snapshot: disk=accessible, "
                    "memory_items=0, tools=echo,time, "
                    "recovery_incidents=0, watchdog=active"
                ),
                verification="Status collected",
            ),
            PlanStep(
                identifier="demo-analyze",
                objective="Analyze collected system data [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Analysis: All monitored components healthy. "
                    "No crash loops. No anomalies. Baseline nominal."
                ),
                verification="Analysis complete",
            ),
            PlanStep(
                identifier="demo-report",
                objective="Produce final status report [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Status report: SYSTEM NOMINAL. "
                    "Runtime: reachable. Brain: demo (no real AI). "
                    "Safety gates: active. All checks passed."
                ),
                verification="Report produced",
            ),
        ]

    def _network_steps(self) -> list[PlanStep]:
        """Two-step network check: probe → report."""
        return [
            PlanStep(
                identifier="demo-net-probe",
                objective="Probe local network state [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Network probe: state=offline (no live Internet probes in demo). "
                    "Local interfaces: present. LAN: not probed in demo mode. "
                    "Outbound policy: restricted (local-only)."
                ),
                verification="Network probe complete",
            ),
            PlanStep(
                identifier="demo-net-report",
                objective="Produce network connectivity report [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Network report: JARVIS operates in local-only mode. "
                    "No external APIs are enabled. "
                    "LocalNetworkFallback interface: stubbed (Raspberry Pi hardware not present). "
                    "Recommendation: configure a local provider at 127.0.0.1 or ::1."
                ),
                verification="Network report ready",
            ),
        ]

    def _memory_steps(self, goal: str) -> list[PlanStep]:
        """Two-step memory workflow: store → confirm."""
        # Extract the content to remember if possible (best-effort heuristic)
        gl = goal.lower()
        content_hint = ""
        for marker in ("remember that ", "remember ", "store that ", "store "):
            if marker in gl:
                idx = gl.index(marker) + len(marker)
                content_hint = goal[idx:].strip()
                break
        if not content_hint:
            content_hint = goal

        return [
            PlanStep(
                identifier="demo-memory-store",
                objective="Store fact in MemoryManager [DEMO]",
                tool_name="echo",
                argument=(
                    f"[DEMO] MemoryManager.remember() called. "
                    f"Content: '{content_hint[:80]}'. "
                    "Stored as memory item #DEMO-001. "
                    "Persisted to local JSON store."
                ),
                verification="Memory stored",
            ),
            PlanStep(
                identifier="demo-memory-confirm",
                objective="Confirm memory retrieval [DEMO]",
                tool_name="echo",
                argument=(
                    f"[DEMO] Memory recall: "
                    f"#{1} — {content_hint[:80]}. "
                    "Item retrievable via semantic search. "
                    "MemoryStore integrity: OK."
                ),
                verification="Memory confirmed",
            ),
        ]

    def _security_steps(self) -> list[PlanStep]:
        """Four-step security pipeline: sentinel → investigate → posture → commander."""
        return [
            PlanStep(
                identifier="demo-sentinel",
                objective="Run SecuritySentinel: process + network snapshot [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] SecuritySentinel: process snapshot captured. "
                    "Network interfaces enumerated. "
                    "0 anomalies flagged in this demo run. "
                    "Heuristics: all within baseline thresholds."
                ),
                verification="Events collected",
            ),
            PlanStep(
                identifier="demo-investigate",
                objective="Run SecurityInvestigator: correlate events [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] SecurityInvestigator: 0 events correlated. "
                    "Timeline: clean. Risk level: INFO. "
                    "Evidence vs assumptions: 0 evidence items, 0 assumptions. "
                    "No suspicious patterns found."
                ),
                verification="Investigation complete",
            ),
            PlanStep(
                identifier="demo-posture",
                objective="Run SecurityTestAgent: local posture check [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] SecurityTestAgent: posture check on authorized local target. "
                    "World-writable paths: none found. "
                    "Env var audit: no credentials in names. "
                    "Hostname resolution: responds locally. "
                    "Platform: acceptable."
                ),
                verification="Posture check complete",
            ),
            PlanStep(
                identifier="demo-commander",
                objective="SecurityCommander: produce unified security report [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] SecurityCommander report: "
                    "SECURE (demo assessment). "
                    "Alerts: 0. Findings: 0. Severity: INFO. "
                    "All safety gates intact. "
                    "No destructive actions taken or proposed."
                ),
                verification="Security report ready",
            ),
        ]

    def _planning_steps(self) -> list[PlanStep]:
        """Two-step planning demo: generate → verify."""
        return [
            PlanStep(
                identifier="demo-plan",
                objective="Generate demo plan structure [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Plan generated: 3 phases identified. "
                    "Phase 1: assess current state. "
                    "Phase 2: identify gaps. "
                    "Phase 3: produce prioritized action list. "
                    "All steps operate within local-only safety boundary."
                ),
                verification="Plan generated",
            ),
            PlanStep(
                identifier="demo-plan-verify",
                objective="Verify plan completeness and safety [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Plan verification: complete. "
                    "No external API calls required. "
                    "No destructive actions proposed. "
                    "Planner approved plan for execution."
                ),
                verification="Plan verified",
            ),
        ]

    def _generic_steps(self, goal: str) -> list[PlanStep]:
        """Two-step fallback for unrecognised goals."""
        truncated = goal[:60]
        return [
            PlanStep(
                identifier="demo-step-1",
                objective=f"Demo step 1: process goal [DEMO]",
                tool_name="echo",
                argument=(
                    f"[DEMO] Processing goal: '{truncated}'. "
                    "AgentOrchestrator selected: standard executor. "
                    "Executing within local safe-tool boundary."
                ),
                verification="Step 1 complete",
            ),
            PlanStep(
                identifier="demo-step-2",
                objective="Demo step 2: verify and summarise [DEMO]",
                tool_name="echo",
                argument=(
                    "[DEMO] Verification complete. "
                    "Goal processed without real AI involvement. "
                    "Result: demo output only. No real data accessed."
                ),
                verification="Verified",
            ),
        ]
