"""DemoBrain and DemoProvider: deterministic demonstration brain.

DEMO MODE — NO REAL AI CONNECTED.

DemoBrain produces scripted, deterministic plans for a small set of
canonical goals.  It clearly identifies itself as a demo and never
claims to be a real language model or connected AI service.

This is NOT a real LLM.  It CANNOT reason about arbitrary goals.
It exists to demonstrate the multi-agent orchestration pipeline
end-to-end in a controlled, repeatable way.
"""

from __future__ import annotations

from ..agent.brain import AIProvider, Brain, BrainUnavailableError
from .models import (
    AgentReport,
    CodeChange,
    ExecutionReport,
    ImprovementProposal,
    Plan,
    PlanStep,
)


DEMO_PROVIDER_NAME = "demo"
DEMO_LABEL = "DEMO MODE — NO REAL AI CONNECTED"


class DemoProvider(AIProvider):
    """Deterministic demo AI provider.

    Returns scripted responses for a small set of known patterns.
    Always identifies outputs as demo-generated.
    """

    @property
    def provider_name(self) -> str:
        return DEMO_PROVIDER_NAME

    def complete(self, prompt: str) -> str:
        """Return a deterministic demo response (not AI-generated)."""
        return (
            f"[{DEMO_LABEL}]\n"
            "This is a scripted demo response. "
            "No language model processed this prompt."
        )

    def is_available(self) -> bool:
        return True


class DemoBrain(Brain):
    """Deterministic Brain implementation for demo/testing purposes.

    Produces scripted plans that exercise the full orchestration pipeline
    without requiring a real AI provider.  All outputs are clearly labelled
    as DEMO.

    Supported canonical goals (case-insensitive substring match):
    - "check" / "status" / "behaving"  → system status check plan
    - "security" / "safe"              → defensive security plan
    - "plan" / "next steps"            → planning demo plan
    - anything else                    → generic demo plan
    """

    @property
    def provider_name(self) -> str:
        return DEMO_PROVIDER_NAME

    def is_available(self) -> bool:
        return True

    def plan(self, goal: str, context: tuple[str, ...] = ()) -> Plan:
        """Produce a deterministic demo plan for the given goal."""
        steps = self._select_steps(goal)
        return Plan(
            goal=f"[{DEMO_LABEL}] {goal}",
            steps=tuple(steps),
            provider=self.provider_name,
        )

    def generate_code(self, request: "CodeGenerationRequest") -> tuple[CodeChange, ...]:  # type: ignore[name-defined]
        """Return a trivial demo code change — clearly labelled."""
        return (
            CodeChange(
                path=request.allowed_files[0] if request.allowed_files else "demo_change.py",
                content=(
                    f"# {DEMO_LABEL}\n"
                    f"# Demo code change for goal: {request.goal}\n"
                    "# This file was NOT generated by a real AI.\n"
                ),
            ),
        )

    def propose_improvement(
        self,
        report: ExecutionReport,
        context: tuple[str, ...] = (),
    ) -> ImprovementProposal:
        """Return a scripted improvement proposal — clearly labelled."""
        return ImprovementProposal(
            title=f"[{DEMO_LABEL}] Demo improvement for: {report.goal}",
            rationale=(
                "This is a scripted demo proposal. "
                "A real AI would analyze the execution report and generate improvements."
            ),
            changes=(),
            provider=self.provider_name,
        )

    # ------------------------------------------------------------------
    # Step library
    # ------------------------------------------------------------------

    def _select_steps(self, goal: str) -> list[PlanStep]:
        gl = goal.lower()
        if any(kw in gl for kw in ("check", "status", "behav", "normal")):
            return self._system_check_steps()
        if any(kw in gl for kw in ("security", "safe", "threat", "suspicious")):
            return self._security_steps()
        if any(kw in gl for kw in ("plan", "next step", "prepare")):
            return self._planning_steps()
        return self._generic_steps(goal)

    def _system_check_steps(self) -> list[PlanStep]:
        return [
            PlanStep(
                identifier="demo-collect",
                objective="Collect local system status [DEMO]",
                tool_name="time",
                argument="",
                verification="Status collected",
            ),
            PlanStep(
                identifier="demo-analyze",
                objective="Analyze collected status [DEMO]",
                tool_name="time",
                argument="",
                verification="Analysis complete",
            ),
            PlanStep(
                identifier="demo-report",
                objective="Produce status report [DEMO]",
                tool_name="time",
                argument="",
                verification="Report produced",
            ),
        ]

    def _security_steps(self) -> list[PlanStep]:
        return [
            PlanStep(
                identifier="demo-sentinel",
                objective="Run SecuritySentinel event collection [DEMO]",
                tool_name="time",
                argument="",
                verification="Events collected",
            ),
            PlanStep(
                identifier="demo-investigate",
                objective="Run SecurityInvestigator analysis [DEMO]",
                tool_name="time",
                argument="",
                verification="Investigation complete",
            ),
            PlanStep(
                identifier="demo-check",
                objective="Run SecurityTestAgent posture check [DEMO]",
                tool_name="time",
                argument="",
                verification="Posture check complete",
            ),
            PlanStep(
                identifier="demo-commander",
                objective="SecurityCommander produces unified report [DEMO]",
                tool_name="time",
                argument="",
                verification="Report ready",
            ),
        ]

    def _planning_steps(self) -> list[PlanStep]:
        return [
            PlanStep(
                identifier="demo-plan",
                objective="Generate demo plan [DEMO]",
                tool_name="time",
                argument="",
                verification="Plan generated",
            ),
            PlanStep(
                identifier="demo-verify",
                objective="Verify demo plan [DEMO]",
                tool_name="time",
                argument="",
                verification="Plan verified",
            ),
        ]

    def _generic_steps(self, goal: str) -> list[PlanStep]:
        return [
            PlanStep(
                identifier="demo-step-1",
                objective=f"Demo step 1 for goal: {goal[:60]} [DEMO]",
                tool_name="time",
                argument="",
                verification="Step 1 complete",
            ),
            PlanStep(
                identifier="demo-step-2",
                objective="Demo verification step [DEMO]",
                tool_name="time",
                argument="",
                verification="Verified",
            ),
        ]
